### ISSUE TITLE
アイデア出し

### ISSUE THREAD

**Issue by tyamanak** [42Tokyo/born2remote-stayhome#1]
issue再び立てておきます。
- Markdownが使えます！
- 書き方はおまかせします！
- 1/4くらいバカっぽいアイデアが混ざってると良いそうです！

**Comment by tyamanak** [comment]
### テーマ

- コミュニケーション促進
    - しばらくオンライン上でのコミュニケーションが続きそうなので、普段コミュニケーション取ってないような人達とも仲良くなれるツールがあればいいのかなと

### 具体案

1. 格ゲー対戦管理bot
    - 対戦ゲームの、ゲーム毎の戦績を管理出来るDiscordBOT
    - 基本的にはコマンドで管理
        - ゲーム開始時：@gamebot start streetfigter5 login1 login2
            - 自動的にgameIDが発行される
        - ゲーム中：@gamebot win gameID login1
        - ゲーム終了：@gamebot end gameID
        - など…
2. ランダムコミュニケーション生成bot
    - 誰かと雑談したいときに活用するbot
    - botにコマンドを送るとランダムに誰かとマッチングしてくれる
        - マッチング要望が飛んできたユーザーは制限時間内にYesかNoを選択
    - そのあとダイレクトメッセージで会話出来る
    - 制限時間が来たら自動的に解散？
    - 単なる雑談でも、質問でも使えそう？

**Comment by tyamanak** [comment]
### キャンパスでDJが出来るbot
- botにMentionでYoutubeのURLを投げると、自動的にキャンパス内のBGMとして再生してくれるbot
- カラオケのように曲は投げた順でストックされる
- 曲のリストを取得したり、削除することもMentionで可能にする

**Comment by tyamanak** [comment]
### 42人生ゲーム
- 42のボードゲーム版
- 42のログインを持つ人だけが遊べる
- cursusのようなボード上を舞台に人生ゲーム（のようなもの）をプレイできる
- 所々に課題があり、プレイ中にコードを書かなければいけない
- 書いたコードがその場で他のプレイヤーにレビューされ、その評価に応じてリソース（wallet）を貰える

**Comment by ywake** [comment]
## レビューが連続で入らないようにしたい
1. 42APIで一定時間おきにスロットの状態をチェック
2. レビュー入ったのを検知したら、APIでスロットを書き換え間隔をあける

**Comment by ywake** [comment]
## 42tokyoからのトーキョータワーがまた見たい
* 42tokyoにドローン用意
* ドローンからの映像を常時youtube配信
* ドローンとカメラをyoutubeコメント等で操作

**Comment by kazoogg** [comment]
**デートプランに困った人必見！**

全然違うかもですが…

デートプランが下手な人に向け
遠隔でデートプランを考えるのが得意な人をマッチングする
デートに特化したコミュニティー的な…

**Comment by kazoogg** [comment]
トイレパニック

ノマドワーカー向けに、カフェでトイレに行きたいとき、
パソコンを置いていくのは心もとない
なので、ソレをみんなで見るサービス
