### ISSUE TITLE
[Dev]スタンプギビング機能

### ISSUE THREAD

**Issue by tyamanak** [42Tokyo/born2remote-stayhome#10]
- [x] 仕様の検証
- [x] コーディング

---

#### 概要

- たくさんのスタンプを集める投稿＝コミュニティへの貢献と考えて、1日1回、スタンプの数に応じてbotから通貨が貰える機能

#### 実装の目的

- 小さな感謝の気持ち＝スタンプの贈り合いを促し、コミュニケーションを促進するため

#### 基本仕様

- 前日の0時から23時59分59秒までの投稿を走査し、スタンプが付けられた投稿と、そのスタンプの数を記録
- スタンプひとつにつき、1Giveで、投稿者に対してGiveを配布
- これを毎日決められた時間に繰り返し動作する

**Comment by ywake** [comment]
historyに含める
sender:押した人
receive:押された人
stamp: true

**Comment by ywake** [comment]
## 仕様の検証結果
DiscordのAPIには[スタンプが押された時/解除された時のイベント](https://discordpy.readthedocs.io/ja/latest/api.html#discord.on_reaction_add)が有る
ここで２パターン
* 押されたら加算、解除されたら減算するパターン
  - 加算されたあと全Give使い切ってからスタンプを解除するとマイナスになる
* 押された/解除された、を追跡。一日の終りにGiveを配布するパターン
  - 追跡のデータを扱うのが面倒

**Comment by nook42** [comment]
1で、スタンプ解除で減らす必要はないのでは。
解除ってあまりないと思いますし。

**Comment by tyamanak** [comment]
ジャストアイディアですが、スタンプからの通貨配布は、通貨が配られた感を分かるようにするため＆ゲーム性を少し増すため、昨日の一位を発表するようにした方がいいかもです。
毎日通知する意味も生まれますし。

**Comment by tyamanak** [comment]
上記はプレゼンでの演出を考えたときに、1日一回表彰がある、みたいなことを言えればいいかなという点から着想してます。実装が2になって、さらに難易度あがりそうな気もするので、将来的な機能として検討した、ということにしてもよいかなと思います。

**Comment by ywake** [comment]
減算がないと無限に増えちゃうんですよね。それを許容するかどうか。
スタンプでの加算減算はhistoryにも登録されるので、それを集計するとランキングや表彰には使えそうですね

**Comment by ywake** [comment]
とりあえず減算も記述しておき、要らなかったらコメントアウトで対応してください
あとはhistoryにappendする際ににstampフラグを付けておくように実装します
