### ISSUE TITLE
[Design]送金イメージ

### ISSUE THREAD

**Issue by nook42** [42Tokyo/born2remote-stayhome#14]
①送金者と受金者のプロフィール画像と、通貨アイコンイメージから送金イメージ画像を作る。
②そのイメージを生成するプログラムを作成する。

**Comment by tyamanak** [comment]
アイコンの座標

- 左側
左上 x=180px y=180px
真ん中 x=294px y=294px
右下 x=408px y=408px

- 右側
左上 x=700px y=180px
真ん中 x= 814px y=294px
右下 x=928px y=408px

すべて画像の左上起点。正円でクロップ想定。
バナーは全体で横1100px 縦670px。
