### ISSUE TITLE
[Design] botデザイン

### ISSUE THREAD

**Issue by nook42** [42Tokyo/born2remote-stayhome#15]

**Comment by tyamanak** [comment]
- アイコンとしては亀山さんの絵（一番有名なヤツ）がDiscordのアカウントアイコンとして表示される
- 全身絵もできればあった方がいい（使い回しがきくので）

**Comment by tyamanak** [comment]
- 全身絵は下だけ合成で貼り替える（神様っぽい方向）
   - あり物でハマりそうなものがあればそれで
   - いらすとやを使ってみたり？
