### ISSUE TITLE
[Dev]ランキング表示機能実装

### ISSUE THREAD

**Issue by nook42** [42Tokyo/born2remote-stayhome#17]

**Comment by nook42** [comment]
ランキング期間は月！

**Comment by nook42** [comment]
ランキング種類
①保有金額
②送金金額
③スタンプ金額
④プール獲得金額
⑤give獲得金額

**Comment by syamashi** [comment]
どのIssueにもアサイン操作ができないのでコメントで連絡です、こちら着手してみます

**Comment by nook42** [comment]
とりあえず①②の実装が終わったので、プルリクに挑戦します。

**Comment by ywake** [comment]
さっきのコードを反映させるために必要な手順まとめましたので、参照してください！
エラー出たらまたDiscordとかで

#### 1. このリポジトリをクローンする
* `git clone https://github.com/42Tokyo/born2remote-stayhome.git`

#### 2. 自分の作業用に新しいブランチを作る
* `git checkout -b my_new_branch`
  - `my_new_branch`の部分は好きなように変えて下さい！

#### 3. コードを書く
* ランキング表示機能の部分を付け足す

#### 4. コミット（ゲームで言えばセーブ）
1. `git add .`
2. `git commit -m "comment"`
  - `comment`部分は好きなように、人にわかりやすく

#### 5. プッシュ（アップロード）
* `git push origin my_new_branch`

#### 6. プルリクエスト
* githubのcodeページに行くとさっきプッシュしたブランチのプルリクエストがサジェストされている。
  - サジェストが見つからないときはbranch一覧から（うろ覚え）

**Comment by tyamanak** [comment]
ランキングなのですが、「金額」という呼称は避けた方がよさそうですね（凄くお金感が強くなる）
感謝の気持ち、がベースだというところはずらさないように、Giveを使うようにしていった方がよいと思いますがいかがでしょう？

ランキング名称
①保有金額　→　保有Give
②送金金額　→　送ったGive
③スタンプ金額　→　スタンプで受け取ったGive
④プール獲得金額　→　プールから獲得したGive
⑤give獲得金額　→　総獲得Give

みたいな感じかなと。

**Comment by nook42** [comment]
そうですね・・自分としては、「通貨」というイメージは大事にしたいので・・
うまくバランスを取りたいところです。
①Give富豪ランキング
②Give貢献ランキング
③スタンプ獲得ランキング
④プール獲得ランキング
⑤/give獲得ランキング

⑤は/giveによる送金の獲得金額です。
どうでしょうか？

**Comment by ywake** [comment]
口煩くて申し訳ないですが、取組中の際はこのページ右側のProjects欄の「To Do」となっているところを「In Progress」に変更をお願いします！

**Comment by tyamanak** [comment]
Give富豪いいなぁｗ

最終的に名前は全部並べて、機能と照らしあわせて一気に詰めた方がよさそうですね。
