### ISSUE TITLE
[プレゼン] プレゼン用資料作成

### ISSUE THREAD

**Issue by tyamanak** [42Tokyo/born2remote-stayhome#20]
- [x] 構成作成
- [x] 構成決定
- [x] スライド作成

**Comment by tyamanak** [comment]
みんなのパロットスタンプが通貨に、みたいなイメージ画像は欲しい。

**Comment by tyamanak** [comment]
# ラフ構成

## ゴール

- 目指すべきは…
  - 課題に対するユニークな解決方法としての「感心」
  - 予想外の使い方や見せ方による「笑い」
    - の獲得を狙う



## 構成案

#### タイトル

仮想通貨「Give」

"ピア"ラーニングを加速する、新しい通貨の提案



#### 仮説定義

- 42あるある
  - takeばかりでgiveできない



#### 解決提案

- 仮想通貨「Give」が、これからのあなたの42生活を一変

- 感謝の気持ちを通貨として流通することで、”ピア”ラーニングを加速させよう



#### ユーザー体験（すべて動画デモで説明）

- 基本機能
  - 専用bot「kamecchi」がみんなの残高を管理したり、Giveを移動したりしてくれます
    - 42Tokyoがあるのも亀山さんのおかげ。みんな感謝しましょう。
  - 質問に答えて貰ったことへのお返しに、Give（送金機能）
  - チャットへのお礼にスタンプで、Give（スタンプギビング機能）
- 活用
  - 課題外のコミュニケーションにも活用できる（プール機能）
  - 1ヵ月ごとのランキング発表



#### 技術紹介

- 
   - ※将来的なセキュアなDBの構築はここで紹介



#### 将来的な機能

- nop_botがハッキングで通貨を増やしてくれるイベント実装
- bunjiro-R_botが通貨を減らすイベント実装
- botに課金して使える機能
  - 飲み会をマッチングしてくれたり
  - 課題の質問に回答してくれそうな人を探してくれたり
- APIを公開してみんなで機能を追加出来るようにしたい

#### シメ

- Piscineが終わった今、より「協力」が重要になります。
- 「競争」よりも「協力」を、このサービスで加速できればと思います。
- ありがとうございました！

**Comment by nook42** [comment]
タイトルは、「仮想通貨」といってしまうとどうしてもブロックチェーンをイメージしてしまうので、「42内通貨 Give」でどうでしょうか？

**Comment by nook42** [comment]
仮説定義

42の、他の学校や会社にはない最大の長所は「競争より協力」であること。
Piscineでは、その威力を痛烈に体験できた。

- しかし現状は、Piscineの時に比べると投票がないため、他メンバーにgiveするインセンティブが薄くなっている。

- また今はリモート環境であるため、少しコミュニケーションが薄く、PiscineのSlackに比べるとDiscordのコミュニケーションは希薄になっている気がする。

**Comment by tyamanak** [comment]
さっきボイチャで話しましたが、ひとまず仮想通貨で進めてます。
これより分かりやすい概念がないなーというのと、
想像してたのと違う→けど面白いからヨシってなればよいかなというイメージです。

**Comment by ywake** [comment]
「他、実装予定の機能」ページ
> ゆくゆくは42Network公式機能入りを目指します

この辺で「walletと交換したり…」と小さく触れられると利用イメージが繋がって良いのではないでしょうか
そもそもwalletとの交換って話は消えたんでしたっけ？
