### ISSUE TITLE
[Dev] 送金終了時のスタンプ

### ISSUE THREAD

**Issue by ywake** [42Tokyo/born2remote-stayhome#8]
* [ ] 送金が終わった時、送金指示のメッセージ`/give xxx 10`等に~~スタンプをつける~~画像を送信

**Comment by nook42** [comment]
「送金時のスタンプ表示」はスタンプじゃなくて、画像です。
give ytanooka 42　と書き込むと、Botが送金完了のメッセージを返します。
その時、メッセージに画像を表示させます。送金者と受金者のプロフィール画像と通貨のアイコン画像を使って送金イメージを出せるといいな、と思います。
