### ISSUE TITLE
[Dev] ランダム機能

### ISSUE THREAD

**Issue by tyamanak** [42Tokyo/born2remote-stayhome#9]
- [x] 仕様の検証
- [x] give増加時のコメント
- [x] コーディング

---

#### 概要

- 時々、giveした通貨がランダムに増える機能
  - 減る、も入れようと思ったが、人から人への感謝の気持ちが勝手に減るのはUX的に良くないなと思ったので、増えるに、限定

#### 実装の目的

- ランダムな幸せを加えることで、お互いの感謝の気持ちを少しだけ高揚させることを狙う

#### 基本仕様

- /give login 10 とコマンドを打つと、通常は10の通貨が移動するところを、5%の確率で、10％、20％、30％、50％受け取る量が増える。
- その際、特別な演出として、botからのメッセージと画像が変化する

#### 変化量の出現率

| 変化量                     | 10％ | 20％  | 30％  | 50％   |
| -------------------------- | ---- | ----- | ----- | ------ |
| 出現率                     | 80％ | 10％  | 4％   | 1％    |
| 実際の出現率（全取引×5％） | 4％  | 0.5％ | 0.2％ | 0.05％ |

#### 未決事項

- 各変化量に対してコメントを変えるかどうか　→　変化した時はコメント必要と考えるが、いかがでしょう？
  - その際表示画像も変えるかどうか

**Comment by onoshin44** [comment]
ランダム関数を追加しています。進捗：80%
ランダムでgiveされたものが増加したときのコメントは実装したほうがいいと思いますので、issue追加します。

**Comment by onoshin44** [comment]
機能追加、レビュー済み。
